config/routes.rb
Rails.application.routes.draw do




 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  
  

  
  




  # resources :cart_items
  # resources :carts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :orders,only:[:new,:create,:index,:show]



  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :orders,only:[:new,:create,:index,:show]


  
  # namespace :admins do
  #   resources :ordered_products, only:[:index,:show]
  #   patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
  #   patch "ordered_products/:id/production_update" => "ordered_products#production_update"
  # end

  namespace :admins do
    resources :orders, only:[:index, :show, :update]
  end
  
  
  



  # get 'costomers/index'
  # get 'costomers/show'
  # get 'costomers/edit'
# 3782311ff1cdb6778024e8fd68187ebed5c72e4d
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
  }
    # devise_scope :admin do
  #   get 'admins/sign_in' => 'admins/sessions#new',as: 'new_admin_session'
  #   post 'admins/sign_in' => 'admins/sessions#create',as: 'admin_session'
  #   delete 'admins/sign_out' => 'admins/sessions#destroy',as:'destroy_admin_session'
  # end
   devise_for :costomers, controllers: {
    registrations: 'costomers/registrations',
    sessions: "costomers/sessions",
   }
   #  :controllers => {
   #    :registrations => 'costomers/registrations',
   #    :sessions => 'costomers/sessions',
   #    :passwords => 'costomers/passwords'
   #  }
  devise_scope :costomer do
    post 'costomers/sign_up/confirm' => 'costomers/registrations#confirm'
  end
  # devise_for :costomers, skip: :all
  # devise_scope :cosotomer do
  get 'costomers/sign_in' => 'costomers/sessions#new'
  post'costomers/sign_in' => 'costomers/sessions#create'
  #   delete 'costomers/sign_out' => 'costomers/sessions#destroy'
  #   get 'costomers/sign_up' => 'costomers/registrations#new'
  #   post 'costomers' => 'costomers/registrations#create'
  #   get 'costomers/password/new' => 'costomers/passwords#new'
  # get 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # post 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # put "/costomers/:id/hide" => "costomers#hide", as: 'costomers_hide'
  # end
  namespace :costomers do
    resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :show]
    resources :costomers, only: [:show, :edit, :update]
    resources :cart_items, except:[:index, :show, :new, :edit]
    resources :carts, except:[:index]
    get "/costomers/costomer/withdraw" => "costomers#withdraw"
    put "/costomers/costomer/:id/hide" => "costomers#hide", as: 'costomers_hide'
  end
  root "costomers/homes#top"





  

 

  # resources :products, only: [:index, :show],param: :id

  # devise_scope :costomer do 
  # resources :products, only: [:index, :show]
  # namespace :admins do
  #     resources :genres, only:[:index,:edit,:update,:create]
  #     resources :products, except: [:destroy]
  # end
  # resources :products, only: [:index, :show]
  # resources :products, only: [:index, :show],param: :id
  # devise_scope :costomer do

  # post 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # end
  # put "/costomers/:id/hide" => "costomers#hide", as: 'costomers_hide'd
#   devise_for :admins, controllers: {
#   sessions: 'admins/sessions'
# }
  # resources :products, only: [:index, :show],params: :id
  
  namespace :admins do
      resources :costomers, only:[:index,:show,:edit,:update]
      resources :genres, only:[:index,:edit,:update,:create]
      resources :products, except: [:destroy]
      resources :products, only: [:index, :show],param: :id
      get "admins/homes" => "homes#top"
      resources :orders, only:[:index, :show, :update]
      resources :ordered_products, only:[:index,:show]
      patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
      patch "ordered_products/:id/production_update" => "ordered_products#production_update"
      end
#     resources :ordered_products, only:[:index,:show]
#     resources :orders, only:[:index, :show, :update]
#     patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
#     patch "ordered_products/:id/production_update" => "ordered_products#production_update"
#     resources :costomers, only:[:index,:show,:edit,:update]
#     resources :genres, only:[:index,:edit,:update,:create]
#     resources :products, except: [:destroy]
#     get "admins/homes" => "homes#top"

  
end

app/views/admins/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <nav class='nav navbar-nav navbar-left' >
          <div class="logo_admin">
            <%= link_to (root_path) do %>
                <%= image_tag 'logo.png',:size =>'80x60' %>
            <% end %>
          </div>
        </nav>
      </div>

  <div class="col-xs-9">
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li>管理者（表示確認用）</li>
          <li class="character_position"><%= link_to "商品一覧", admins_products_path,class: 'btn btn-default btn-xs head_bt' %></li>
          <li><%= link_to "会員一覧", admins_costomers_path,class: 'btn btn-default btn-sm admin' %></li>          
          <li><%= link_to "注文履歴一覧", admins_orders_path,class: 'btn btn-default btn-sm head_bt' %></li><!-- 要パス修正 -->
          <li><%= link_to "ジャンル一覧", admins_genres_path,class: 'btn btn-default btn-sm head_bt' %></li>
          <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'btn btn-default btn-xs head_bt' %></li>
      </ul>

      <div class="pull-right">
        <div class="row">
          <div class='col-xs-8'></div>
          <div class='col-xs-4'>
            <div class="input-group">
              <input type="text" class="form-control">
              <span class="input-group-btn">
                <button type="button" class="btn btn-default">
                  <i class="fas fa-search"></i>
                </button>
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">会員</a></li>
                  <li><a href="#">商品</a></li>
                  <li><a href="#">注文</a></li>
                </ul>
              </span>
            </div>
          </div>
        </div>
      </div>


      </div>

    </nav>
   </div>
  </div>
</header>