config/routes.rb
Rails.application.routes.draw do




 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  
  

  
  




  # resources :cart_items
  # resources :carts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :orders,only:[:new,:create,:index,:show]



  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :orders,only:[:new,:create,:index,:show]


  
  # namespace :admins do
  #   resources :ordered_products, only:[:index,:show]
  #   patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
  #   patch "ordered_products/:id/production_update" => "ordered_products#production_update"
  # end

  namespace :admins do
    resources :orders, only:[:index, :show, :update]
  end
  
  
  



  # get 'costomers/index'
  # get 'costomers/show'
  # get 'costomers/edit'
# 3782311ff1cdb6778024e8fd68187ebed5c72e4d
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
  }
    # devise_scope :admin do
  #   get 'admins/sign_in' => 'admins/sessions#new',as: 'new_admin_session'
  #   post 'admins/sign_in' => 'admins/sessions#create',as: 'admin_session'
  #   delete 'admins/sign_out' => 'admins/sessions#destroy',as:'destroy_admin_session'
  # end
   devise_for :costomers, controllers: {
    registrations: 'costomers/registrations',
    sessions: "costomers/sessions",
   }
   #  :controllers => {
   #    :registrations => 'costomers/registrations',
   #    :sessions => 'costomers/sessions',
   #    :passwords => 'costomers/passwords'
   #  }
  devise_scope :costomer do
    post 'costomers/sign_up/confirm' => 'costomers/registrations#confirm'
  end
  # devise_for :costomers, skip: :all
  # devise_scope :cosotomer do
  get 'costomers/sign_in' => 'costomers/sessions#new'
  post'costomers/sign_in' => 'costomers/sessions#create'
  #   delete 'costomers/sign_out' => 'costomers/sessions#destroy'
  #   get 'costomers/sign_up' => 'costomers/registrations#new'
  #   post 'costomers' => 'costomers/registrations#create'
  #   get 'costomers/password/new' => 'costomers/passwords#new'
  # get 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # post 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # put "/costomers/:id/hide" => "costomers#hide", as: 'costomers_hide'
  # end
  namespace :costomers do
    resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :show]
    resources :costomers, only: [:show, :edit, :update]
    resources :cart_items, except:[:index, :show, :new, :edit]
    resources :carts, except:[:index]
    get "/costomers/costomer/withdraw" => "costomers#withdraw"
    put "/costomers/costomer/:id/hide" => "costomers#hide", as: 'costomers_hide'
  end
  root "costomers/homes#top"





  

 

  # resources :products, only: [:index, :show],param: :id

  # devise_scope :costomer do 
  # resources :products, only: [:index, :show]
  # namespace :admins do
  #     resources :genres, only:[:index,:edit,:update,:create]
  #     resources :products, except: [:destroy]
  # end
  # resources :products, only: [:index, :show]
  # resources :products, only: [:index, :show],param: :id
  # devise_scope :costomer do

  # post 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # end
  # put "/costomers/:id/hide" => "costomers#hide", as: 'costomers_hide'd
#   devise_for :admins, controllers: {
#   sessions: 'admins/sessions'
# }
  # resources :products, only: [:index, :show],params: :id
  
  namespace :admins do
      resources :costomers, only:[:index,:show,:edit,:update]
      resources :genres, only:[:index,:edit,:update,:create]
      resources :products, except: [:destroy]
      resources :products, only: [:index, :show],param: :id
      get "admins/homes" => "homes#top"
      resources :orders, only:[:index, :show, :update]
      resources :ordered_products, only:[:index,:show]
      patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
      patch "ordered_products/:id/production_update" => "ordered_products#production_update"
      end
#     resources :ordered_products, only:[:index,:show]
#     resources :orders, only:[:index, :show, :update]
#     patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
#     patch "ordered_products/:id/production_update" => "ordered_products#production_update"
#     resources :costomers, only:[:index,:show,:edit,:update]
#     resources :genres, only:[:index,:edit,:update,:create]
#     resources :products, except: [:destroy]
#     get "admins/homes" => "homes#top"

  
end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :name, presence: { message: 'ジャンル名を入力してください' }
	validates :is_valid, inclusion: { in: [true, false] }

	has_many :products, dependent: :destroy
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
	before_action :if_not_admin

	def index
		@genres = Genre.all
    	@genre = Genre.new
	end

	def create
		@genre=Genre.new(genre_params)
		if @genre.save
      		redirect_to admins_genres_path,notice: '新規ジャンルを登録しました'
    	else
      		@genres = Genre.all
      		render 'index'
        end
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
	    @genre = Genre.find(params[:id])
	    if @genre.update(genre_params)
	       redirect_to admins_genres_path,notice: 'ジャンルを編集しました'
	    else
	      render 'edit'
	    end
	end

	private
	def genre_params
      	params.require(:genre).permit(:name, :is_valid)
    end
    #adminコントローラに全部入れたい
    def if_not_admin
    	redirect_to new_admin_session_path unless admin_signed_in?
    end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/views/admins/genres/edit.html.erb
<%= render 'layouts/errors', obj: @genre %>

<div class="row">
	<div class='col-xs-6'>

		<!-- ジャンル編集フォーム -->
		<h3 style='margin-bottom: 30px;'>ジャンル編集</h3>
		<%= form_for(@genre,url: admins_genre_path(@genre)) do |f| %>
		  <div class="field row">
		  	<!-- ジャンルテキスト入力フォーム -->
		  	<div class='col-xs-5'>
		     <%= f.label :name,"ジャンル" %>
		     <%= f.text_field :name, class: 'genre_name'%>
		    </div>

		    <!-- 有効無効ラジオボタン-->
		    <div class='col-xs-6'>
		      <%= f.radio_button :is_valid, :true, checked: "checked" %>
    		  <%= f.label :is_valid,"有効" %>
    		  <%= f.radio_button :is_valid, :false %>
    		  <%= f.label :is_valid,"無効" %>
    		

		    <%= f.submit "変更を保存する", class: 'btn btn-primary'%>
		    </div>
		  </div>
		<% end %>

	</div>
</div>

app/views/admins/genres/index.html.erb
<%= render 'layouts/errors', obj: @genre %>

<div class="row">
	<div class='col-xs-6'>

		<!-- ジャンル追加フォーム -->
		<h3 style='margin-bottom: 30px;'>ジャンル一覧・追加</h3>
		<%= form_for(@genre,url: admins_genres_path) do |f| %>
		  <div class="field row">
		  	<!-- ジャンルテキスト入力フォーム -->
		  	<div class='col-xs-5'>
		      <%= f.label :name,"ジャンル" %>
		      <%= f.text_field :name, class: 'genre_name' %>
			</div>

		    <!-- 有効無効ラジオボタン-->
		    <div class='col-xs-6'>
		      <%= f.radio_button :is_valid, :true, checked: "checked" %>
    		  <%= f.label :is_valid,"有効" %>
    		  <%= f.radio_button :is_valid, :false %>
    		  <%= f.label :is_valid,"無効" %>
    		  <%= f.submit "追加", class: 'btn btn-primary'%>
		   </div>
		  </div>
		<% end %>

		<!-- ジャンル一覧表示 -->
		<table class='table table-hover table-inverse'>
			<thead>
			    <tr> 
			      <th>ジャンル</th>
			      <th>状態</th>
			      <th></th>
			      <th colspan="3"></th>
			    </tr>
			</thead>
			<tbody>
				<% @genres.each do |genre| %>
					<tr>
						<td><%= genre.name %></td>
						<td><%= (genre.is_valid==true) ? "有効" : "無効" %></td>
						<td><%= link_to "編集する", edit_admins_genre_path(genre), class: 'btn-sm btn-success edit_genres_' %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	
	</div>
</div>