config/routes.rb
Rails.application.routes.draw do




 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  
  

  
  




  # resources :cart_items
  # resources :carts, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :orders,only:[:new,:create,:index,:show]



  post "orders/confirm" => "orders#confirm"
  get "orders/complete" => "orders#complete"
  resources :orders,only:[:new,:create,:index,:show]


  
  # namespace :admins do
  #   resources :ordered_products, only:[:index,:show]
  #   patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
  #   patch "ordered_products/:id/production_update" => "ordered_products#production_update"
  # end

  namespace :admins do
    resources :orders, only:[:index, :show, :update]
  end
  
  
  



  # get 'costomers/index'
  # get 'costomers/show'
  # get 'costomers/edit'
# 3782311ff1cdb6778024e8fd68187ebed5c72e4d
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
  }
    # devise_scope :admin do
  #   get 'admins/sign_in' => 'admins/sessions#new',as: 'new_admin_session'
  #   post 'admins/sign_in' => 'admins/sessions#create',as: 'admin_session'
  #   delete 'admins/sign_out' => 'admins/sessions#destroy',as:'destroy_admin_session'
  # end
   devise_for :costomers, controllers: {
    registrations: 'costomers/registrations',
    sessions: "costomers/sessions",
   }
   #  :controllers => {
   #    :registrations => 'costomers/registrations',
   #    :sessions => 'costomers/sessions',
   #    :passwords => 'costomers/passwords'
   #  }
  devise_scope :costomer do
    post 'costomers/sign_up/confirm' => 'costomers/registrations#confirm'
  end
  # devise_for :costomers, skip: :all
  # devise_scope :cosotomer do
  get 'costomers/sign_in' => 'costomers/sessions#new'
  post'costomers/sign_in' => 'costomers/sessions#create'
  #   delete 'costomers/sign_out' => 'costomers/sessions#destroy'
  #   get 'costomers/sign_up' => 'costomers/registrations#new'
  #   post 'costomers' => 'costomers/registrations#create'
  #   get 'costomers/password/new' => 'costomers/passwords#new'
  # get 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # post 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # put "/costomers/:id/hide" => "costomers#hide", as: 'costomers_hide'
  # end
  namespace :costomers do
    resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
    resources :products, only: [:index, :show]
    resources :costomers, only: [:show, :edit, :update]
    resources :cart_items, except:[:index, :show, :new, :edit]
    resources :carts, except:[:index]
    get "/costomers/costomer/withdraw" => "costomers#withdraw"
    put "/costomers/costomer/:id/hide" => "costomers#hide", as: 'costomers_hide'
  end
  root "costomers/homes#top"





  

 

  # resources :products, only: [:index, :show],param: :id

  # devise_scope :costomer do 
  # resources :products, only: [:index, :show]
  # namespace :admins do
  #     resources :genres, only:[:index,:edit,:update,:create]
  #     resources :products, except: [:destroy]
  # end
  # resources :products, only: [:index, :show]
  # resources :products, only: [:index, :show],param: :id
  # devise_scope :costomer do

  # post 'cosotmers/sign_up/confirm' => 'costomers/registrations#confirm'
  # end
  # put "/costomers/:id/hide" => "costomers#hide", as: 'costomers_hide'd
#   devise_for :admins, controllers: {
#   sessions: 'admins/sessions'
# }
  # resources :products, only: [:index, :show],params: :id
  
  namespace :admins do
      resources :costomers, only:[:index,:show,:edit,:update]
      resources :genres, only:[:index,:edit,:update,:create]
      resources :products, except: [:destroy]
      resources :products, only: [:index, :show],param: :id
      get "admins/homes" => "homes#top"
      resources :orders, only:[:index, :show, :update]
      resources :ordered_products, only:[:index,:show]
      patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
      patch "ordered_products/:id/production_update" => "ordered_products#production_update"
      end
#     resources :ordered_products, only:[:index,:show]
#     resources :orders, only:[:index, :show, :update]
#     patch "ordered_products/:id/order_update" => "ordered_products#order_update", as: 'order_update'
#     patch "ordered_products/:id/production_update" => "ordered_products#production_update"
#     resources :costomers, only:[:index,:show,:edit,:update]
#     resources :genres, only:[:index,:edit,:update,:create]
#     resources :products, except: [:destroy]
#     get "admins/homes" => "homes#top"

  
end

app/models/ordered_product.rb
class OrderedProduct < ApplicationRecord
    enum production_status: { 着手不可: 0, 制作待ち: 1, 製作中: 2, 制作完了: 3 }
    
    belongs_to :order, optional: true
    belongs_to :product
end

app/controllers/admins/ordered_products_controller.rb
class Admins::OrderedProductsController < ApplicationController
    def index
        @orders = Order.all
      end
    
      def show
        @order = Order.find(params[:id])
        
      end
    
      def order_update
       @order = Order.find(params[:id])
       @order.update(admin_ordered_products_params)
       redirect_to admins_orders_path
      end
    
      def production_update
        @ordered_product = OrderedProduct.find(params[:id])
        @ordered_product.update(admins_ordered_products_params)
        redirect_to admins_orders_path
      end
    
      private
        def admin_ordered_products_params
          params.require(:order).permit(:order_status)
        end

        def admins_ordered_products_params
          params.require(:ordered_product).permit(:production_status)
        end
end

app/helpers/admins/ordered_products_helper.rb
module Admins::OrderedProductsHelper
end

app/views/admins/ordered_products/index.html.erb
<h3>注文履歴一覧</h3>
<table class="table table-bordered">
    <thead>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
    </thead>
    <tbody>
        <% @orders.each do |order| %>
            <tr>
                <td><%= link_to admins_ordered_product_path(order) do %>
                    <%= order.created_at.strftime('%Y/%m/%d') %>
                <% end %></td>
                <td></td>
                <td></td>
                <td><%= order.order_status %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admins/ordered_products/show.html.erb
<div class="container">
    <div class="row">
        <h3>注文履歴詳細</h3>
        <span>購入者</span>
        
        <span>配送先</span>
        
        
        <span>支払方法</span>
        <%= @order.pay_method %><br>
        <span>注文ステータス</span>
        <%= form_for @order, url:  admins_order_update_path(@order) do |f| %>
        <%= f.select :order_status,Order.order_statuses.keys.to_a, {} %>
        <%= f.submit "更新" %>
        <% end %>
    </div>
    <div class="row">
        <div class="col-xs-9">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>商品名</th>
                        <th>単価（税込）</th>
                        <th>数量</th>
                        <th>小計</th>
                        <th>制作ステータス</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            
                            <%= select :production_status,:name,OrderedProduct.production_statuses.keys.to_a %></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-xs-3">
            <table>
                <tr>
                    <th>商品合計</th>
                    <td><%= @order.billing_amount %></td>
                </tr>
                <tr>
                    <th>送料</th>
                    <td>800</td>
                </tr>
                <tr>
                    <th>請求額合計</th>
                    <td><%= @order.billing_amount.to_i + 800 %></td>
                </tr>
            </table>
        </div>
</div>